# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - run: npm install
    - run: npm test

  deploy:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{secrets.RENDER_SERVICE_ID}}
          api_key: ${{secrets.RENDER_API_KEY}}
